# -*- coding: utf-8 -*-
"""features_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0HwGnDIEQtK9t26Cjk7z14psxDtFaDc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import kagglehub
from cleaning_01 import clean_data
import kagglehub

path = kagglehub.dataset_download("prevek18/ames-housing-dataset")
df = pd.read_csv(path + "/AmesHousing.csv")
df

"""# .One-Hot Encode

Applies one-hot encoding to selected categorical columns and returns the updated DataFrame.
"""

def one_hot_encode(df):
    cols = ["Lot Shape", "House Style"]
    df = pd.get_dummies(df, columns=cols, drop_first=True)
    return df

"""# Ordinal Encode

Encodes the "Kitchen Qual" column by mapping ordered categories to numerical values and returns the updated DataFrame.
"""

def ordinal_encode(df):
    qual_map = {"Po": 1, "Fa": 2, "TA": 3, "Gd": 4, "Ex": 5}
    df["Kitchen Qual"] = df["Kitchen Qual"].map(qual_map)
    return df

"""# • Scale

Scales selected numerical features using StandardScaler by fitting on training data and applying the same transformation to test data, then returns both datasets.
"""

def scale_features(train_df, test_df):
    train_df = train_df.copy()
    test_df = test_df.copy()

    scaler = StandardScaler()
    scale_cols = ["Gr Liv Area", "Lot Area"]

    train_df[scale_cols] = scaler.fit_transform(train_df[scale_cols])
    test_df[scale_cols] = scaler.transform(test_df[scale_cols])

    return train_df, test_df

"""# 2 Domain Features

Creates new domain features by calculating price per square foot and total area, then returns the updated DataFrame.
"""

def domain_feature(df):
    df["Price_per_Sqft"] = df["SalePrice"] / df["Gr Liv Area"].replace(0, np.nan)
    df["TotalArea"] = df["Gr Liv Area"] + df["Total Bsmt SF"]
    return df

"""# 1 Interaction Feature

Creates a new feature by multiplying overall quality with living area to capture their interaction, then returns the updated DataFrame.
"""

def interaction_feature(df):
    df["quality_x_area"] = df["Overall Qual"] * df["Gr Liv Area"]
    return df

"""# log_transfrom

Applies a log transformation to "Gr Liv Area" to reduce skewness, visualizes before and after with histograms, and returns the updated DataFrame.
"""

def log_transform(df):


    plt.figure(figsize = (6, 4))
    plt.hist(df["Gr Liv Area"], bins = 30)
    plt.title("Gr Liv Area Before Log Transform")
    plt.xlabel("Gr Liv Area")
    plt.ylabel("Count")
    plt.show()

    df["Gr Liv Area Log"] = np.log1p(df["Gr Liv Area"])

    plt.figure(figsize = (6, 4))
    plt.hist(df["Gr Liv Area Log"], bins = 30)
    plt.title("Gr Liv Area After Log Transform")
    plt.xlabel("Gr Liv Area Log")
    plt.ylabel("Count")
    plt.show()

    return df

"""# Bin

Creates a new feature "House Age" and bins it into age groups ("New", "Recent", "Old"), then returns the updated DataFrame.
"""

def binning_feature(df):
    df = df.copy()

    df["House Age"] = 2026 - df["Year Built"]

    df["Age Group"] = pd.cut(
        df["House Age"],
        bins = [0, 20, 50, 200],
        labels = ["New", "Recent", "Old"]
    )

    return df

""".Train Test Split

Splits the DataFrame into training and testing sets (80% train, 20% test) and returns both.
"""

def split_data(df):
    train_df, test_df = train_test_split(df, test_size = 0.2, random_state = 42)
    return train_df, test_df

"""# Remove Redundant Features

Removes highly correlated (redundant) features with correlation above 0.95 from training and testing sets, then returns the cleaned datasets and list of dropped columns.
"""

def  remove_Redundant_Features(train_df, test_df):
    corr = train_df.corr(numeric_only=True).abs()

    to_drop = []
    for col in corr.columns:
        for row in corr.index:
            if col != row and corr.loc[row, col] > 0.95:
                if col not in to_drop:
                    to_drop.append(col)

    train_df = train_df.drop(columns=to_drop, errors="ignore")
    test_df = test_df.drop(columns=to_drop, errors="ignore")

    return train_df, test_df, to_drop

"""#clean data

Cleans and preprocesses the dataset by applying one-hot and ordinal encoding, creating domain and interaction features, log transformation, binning, splitting, scaling, and removing redundant features, then returns the training and testing sets.
"""

def clean_data2(path):
    df = clean_data(path)
    df_1 = one_hot_encode(df)
    df_2 = ordinal_encode(df)
    df_3 = domain_feature(df)
    df_3 = interaction_feature(df)
    df_4 = log_transform(df)
    df_5 = binning_feature(df)

    train_df, test_df = split_data(df)
    train_df, test_df = scale_features(train_df, test_df)

    train_df, test_df, dropped_cols = remove_Redundant_Features(train_df, test_df)

    features_df = pd.concat([train_df, test_df]).sort_index()

    print("Dropped columns:", dropped_cols)
    print("Final shape:", features_df.shape)

    return train_df, test_df

path1 = "/content/AmesHousing.csv"
print(clean_data2(path1))